import {StyleSheet} from 'react-native'
import {screenHeight,screenWidth} from '../../Main/fullScreenValue'
const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#f9f8e8'
    },
    topLine:{
        marginTop:30,
        marginLeft:30,
        flexDirection:'row'
    },
    backButtonPosition:{
        marginTop:20
    },
    font:{
        marginLeft:10,
        fontSize:40,
        color:'black',
        fontWeight:'bold'
    },
    univSearch:{
        borderColor:'#a8ce9e',
        borderWidth:3,
        marginLeft:10,
        marginRight:10,
        borderRadius:10,
        paddingLeft:screenWidth*0.05
    },
    rank:{
        marginLeft:10,
        marginRight:10,
        height:screenHeight*0.065,
        marginBottom:20,
        borderWidth:3,
        borderColor:'green',
        borderRadius:10,
        flexDirection:'row',
        backgroundColor:'gray'
        //alignItems:'center',
    },
    itemRank:{
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    itemUniv:{
        flex:3,
        alignItems:'center',
        justifyContent:'center'
    },
    itemPoint:{
        flex:2,
        alignItems:'center',
        justifyContent:'center'
    },
    itemFont:{
        fontSize:screenHeight*0.022,
        color:'white'
    }
})
export default styles